-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION public.artwork_views(artwork_row artworks)
--  RETURNS bigint
--  LANGUAGE sql
--  STABLE
-- AS $function$
--     SELECT SUM(views)
--     FROM editions e
--     WHERE e.artwork_id = artwork_row.id
-- $function$;
